spring:
  thymeleaf:
    cache: true
  main:
    lazy-initialization: true

logging:
  level:
    root: WARN
    io.github.wamukat.thymeleaflet: WARN
    io.github.wamukat.thymeleaflet.infrastructure.web.service: WARN
    io.github.wamukat.thymeleaflet.application.service: WARN
    io.github.wamukat.thymeleaflet.infrastructure.adapter.discovery: WARN

thymeleaflet:
  cache:
    enabled: true
    preload: true
