spring:
  thymeleaf:
    cache: false

server:
  port: ${PORT:6006}

thymeleaflet:
  base-path: /thymeleaflet
  debug: false
  resources:
    template-paths:
      - /templates/
    stylesheets:
      - /css/mypage.css
      - /css/mypage/components.css
    scripts:
      - /js/accordion.js
    cache-duration-seconds: 3600
  security:
    enabled: false
